# Go-NEB Configuration File
#
# This file provides an alternative way to configure Go-NEB which does not involve HTTP APIs.
#
# This file can be supplied to go-neb by the environment variable `CONFIG_FILE=config.yaml`.
# It will force Go-NEB to operate in "config" mode. This means:
#   - Go-NEB will ONLY use the data contained inside this file.
#   - All of Go-NEB's /admin HTTP listeners will be disabled. You will be unable to add new services at runtime.
#   - The environment variable `DATABASE_URL` will be ignored and an in-memory database will be used instead.
#
# This file is broken down into 4 sections which matches the following HTTP APIs:
#   - /configureClient
#   - /configureAuthRealm
#   - /configureService
#   - /requestAuthSession (redirects not supported)

# The list of clients which Go-NEB is aware of.
# Delete or modify this list as appropriate.
# See the docs for /configureClient for the full list of options:
# https://matrix-org.github.io/go-neb/pkg/github.com/matrix-org/go-neb/api/index.html#ClientConfig
clients:
  - UserID: "@113:hs.globekeeper.com"
    AccessToken: "oZpJ1gkpw_Z_O4fWgQ4erUO3QA-guN5oznTVvmC0Jf8"
    DeviceID: "zw_CupXk"
    HomeserverURL: "hs.globekeeper.com"
    Sync: false 
    AutoJoinRooms: false
    DisplayName: "AlertManager Bot"

  - UserID: "@114:hs.globekeeper.com"
    AccessToken: "__oHJprcfToiQtDZk8cy7WipzFtPetMOaHgaFV5ySNE"
    DeviceID: "uFGp8Dy7"
    HomeserverURL: "hs.globekeeper.com"
    Sync: true
    AutoJoinRooms: true
    DisplayName: "Giphy Bot"

  - UserID: "@115:hs.globekeeper.com"
    AccessToken: "rpBZOIULioQu1gQTCHHrLQApd9VQE9df8bIi2E4q9QQ"
    DeviceID: "xnlHcLAe"
    HomeserverURL: "hs.globekeeper.com"
    Sync: false
    AutoJoinRooms: true
    DisplayName: "Wiki Bot"

  - UserID: "@120:hs.globekeeper.com"
    AccessToken: "cnWpQx_zDWwUBHTlj_s3_Kp3DONNPTmoWAkLOy4r9dc"
    DeviceID: "htEkeD28"
    HomeserverURL: "hs.globekeeper.com"
    Sync: true
    AutoJoinRooms: true
    DisplayName: "iosBuild Bot"


# The list of services which Go-NEB is aware of.
# Delete or modify this list as appropriate.
# See the docs for /configureService for the full list of options:
# https://matrix-org.github.io/go-neb/pkg/github.com/matrix-org/go-neb/api/index.html#ConfigureServiceRequest
services:
  - ID: "alertmanager_service"
    Type: "alertmanager"
    UserID: "@113:hs.globekeeper.com"
    Config:
      # This is for information purposes only. It should point to Go-NEB path as follows:
      # `/services/hooks/<base64 encoded service ID>`
      # Where in this case "service ID" is "alertmanager_service"
      # Make sure your BASE_URL can be accessed by the Alertmanager instance!
      webhook_url: "https://hs.globekeeper.com/_globekeeper/connectbot/services/hooks/YWxlcnRtYW5hZ2VyX3NlcnZpY2U"
      # Each room will get the notification with the alert rendered with the given template
      rooms:
        "!Q0ywt7gewijyrOLa:hs.globekeeper.com": # The `Builds` roomId.
          text_template: "{{range .Alerts -}} {{ .Status }} {{index .Labels \"alertname\" }}: {{index .Annotations \"description\"}} {{ end -}}"
          msg_type: "m.text"  # Must be either `m.text` or `m.notice`

  - ID: "giphy_service"
    Type: "giphy"
    UserID: "@114:hs.globekeeper.com" # requires a Syncing client
    Config:
      api_key: "hSG7fp4ofT6UmqgNfob5wSFK3MPA7FWs"
      use_downsized: false

  - ID: "wikipedia_service"
    Type: "wikipedia"
    UserID: "@115:hs.globekeeper.com" # requires a Syncing client
    Config:
