# Go-NEB Configuration File
#
# This file provides an alternative way to configure Go-NEB which does not involve HTTP APIs.
#
# This file can be supplied to go-neb by the environment variable `CONFIG_FILE=config.yaml`.
# It will force Go-NEB to operate in "config" mode. This means:
#   - Go-NEB will ONLY use the data contained inside this file.
#   - All of Go-NEB's /admin HTTP listeners will be disabled. You will be unable to add new services at runtime.
#   - The environment variable `DATABASE_URL` will be ignored and an in-memory database will be used instead.
#
# This file is broken down into 4 sections which matches the following HTTP APIs:
#   - /configureClient
#   - /configureAuthRealm
#   - /configureService
#   - /requestAuthSession (redirects not supported)

# The list of clients which Go-NEB is aware of.
# Delete or modify this list as appropriate.
# See the docs for /configureClient for the full list of options:
# https://matrix-org.github.io/go-neb/pkg/github.com/matrix-org/go-neb/api/index.html#ClientConfig
clients:
  - UserID: "@906:dendrite.stg.globekeeper.com"
    AccessToken: "kbTP-i8j4qOY7NMy_FyrOmxWfhDBV4654cujox0DCdo"
    DeviceID: "yo6SqYk6"
    HomeserverURL: "dendrite.stg.globekeeper.com"
    Sync: false 
    AutoJoinRooms: false
    DisplayName: "AlertManager Bot"

  - UserID: "@907:dendrite.stg.globekeeper.com"
    AccessToken: "3mLa-KErbt9dsGdPXow84pbw-Ko7r7G-kVvhRZy1vhg"
    DeviceID: "IVFFT8Sw"
    HomeserverURL: "dendrite.stg.globekeeper.com"
    Sync: true
    AutoJoinRooms: true
    DisplayName: "Giphy Bot"

  - UserID: "@908:dendrite.stg.globekeeper.com"
    AccessToken: "Kj0CRKNA4pBrnNPCb_dW3plcG1DENpfMs-WNgzx45yE"
    DeviceID: "VcOlPwUm"
    HomeserverURL: "dendrite.stg.globekeeper.com"
    Sync: false
    AutoJoinRooms: true
    DisplayName: "Wiki Bot"


# The list of services which Go-NEB is aware of.
# Delete or modify this list as appropriate.
# See the docs for /configureService for the full list of options:
# https://matrix-org.github.io/go-neb/pkg/github.com/matrix-org/go-neb/api/index.html#ConfigureServiceRequest
services:
  - ID: "alertmanager_service"
    Type: "alertmanager"
    UserID: "@906:dendrite.stg.globekeeper.com"
    Config:
      # This is for information purposes only. It should point to Go-NEB path as follows:
      # `/services/hooks/<base64 encoded service ID>`
      # Where in this case "service ID" is "alertmanager_service"
      # Make sure your BASE_URL can be accessed by the Alertmanager instance!
      webhook_url: "https://dendrite.stg.globekeeper.com/_globekeeper/connectbot/services/hooks/YWxlcnRtYW5hZ2VyX3NlcnZpY2U"
      # Each room will get the notification with the alert rendered with the given template
      rooms:
        "!XFow9eSZVMmBCwUg:dendrite.stg.globekeeper.com": # The `Builds` roomId.
          text_template: "{{range .Alerts -}} {{ .Status }} {{index .Labels \"alertname\" }}: {{index .Annotations \"description\"}} {{ end -}}"
          msg_type: "m.text"  # Must be either `m.text` or `m.notice`

  - ID: "giphy_service"
    Type: "giphy"
    UserID: "@907:dendrite.stg.globekeeper.com" # requires a Syncing client
    Config:
      api_key: "hSG7fp4ofT6UmqgNfob5wSFK3MPA7FWs"
      use_downsized: false

  - ID: "wikipedia_service"
    Type: "wikipedia"
    UserID: "@908:dendrite.stg.globekeeper.com" # requires a Syncing client
    Config:
